# Generated by Django 3.2.2 on 2021-05-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mycontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Mycontact',
            },
        ),
    ]
